//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace Clinic_Management_System
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CMSEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CMSEntities object using the connection string found in the 'CMSEntities' section of the application configuration file.
        /// </summary>
        public CMSEntities() : base("name=CMSEntities", "CMSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CMSEntities object.
        /// </summary>
        public CMSEntities(string connectionString) : base(connectionString, "CMSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CMSEntities object.
        /// </summary>
        public CMSEntities(EntityConnection connection) : base(connection, "CMSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Patient_Reg> Patient_Reg
        {
            get
            {
                if ((_Patient_Reg == null))
                {
                    _Patient_Reg = base.CreateObjectSet<Patient_Reg>("Patient_Reg");
                }
                return _Patient_Reg;
            }
        }
        private ObjectSet<Patient_Reg> _Patient_Reg;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Patient_Reg EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPatient_Reg(Patient_Reg patient_Reg)
        {
            base.AddObject("Patient_Reg", patient_Reg);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CMSModel", Name="Patient_Reg")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Patient_Reg : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Patient_Reg object.
        /// </summary>
        /// <param name="patientID">Initial value of the PatientID property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="dOB">Initial value of the DOB property.</param>
        /// <param name="gender">Initial value of the Gender property.</param>
        /// <param name="address">Initial value of the Address property.</param>
        public static Patient_Reg CreatePatient_Reg(global::System.String patientID, global::System.String firstName, global::System.String dOB, global::System.String gender, global::System.String address)
        {
            Patient_Reg patient_Reg = new Patient_Reg();
            patient_Reg.PatientID = patientID;
            patient_Reg.FirstName = firstName;
            patient_Reg.DOB = dOB;
            patient_Reg.Gender = gender;
            patient_Reg.Address = address;
            return patient_Reg;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PatientID
        {
            get
            {
                return _PatientID;
            }
            set
            {
                if (_PatientID != value)
                {
                    OnPatientIDChanging(value);
                    ReportPropertyChanging("PatientID");
                    _PatientID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("PatientID");
                    OnPatientIDChanged();
                }
            }
        }
        private global::System.String _PatientID;
        partial void OnPatientIDChanging(global::System.String value);
        partial void OnPatientIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Saluation
        {
            get
            {
                return _Saluation;
            }
            set
            {
                OnSaluationChanging(value);
                ReportPropertyChanging("Saluation");
                _Saluation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Saluation");
                OnSaluationChanged();
            }
        }
        private global::System.String _Saluation;
        partial void OnSaluationChanging(global::System.String value);
        partial void OnSaluationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MiddleName
        {
            get
            {
                return _MiddleName;
            }
            set
            {
                OnMiddleNameChanging(value);
                ReportPropertyChanging("MiddleName");
                _MiddleName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MiddleName");
                OnMiddleNameChanged();
            }
        }
        private global::System.String _MiddleName;
        partial void OnMiddleNameChanging(global::System.String value);
        partial void OnMiddleNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NIC
        {
            get
            {
                return _NIC;
            }
            set
            {
                OnNICChanging(value);
                ReportPropertyChanging("NIC");
                _NIC = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NIC");
                OnNICChanged();
            }
        }
        private global::System.String _NIC;
        partial void OnNICChanging(global::System.String value);
        partial void OnNICChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String DOB
        {
            get
            {
                return _DOB;
            }
            set
            {
                OnDOBChanging(value);
                ReportPropertyChanging("DOB");
                _DOB = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("DOB");
                OnDOBChanged();
            }
        }
        private global::System.String _DOB;
        partial void OnDOBChanging(global::System.String value);
        partial void OnDOBChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Age
        {
            get
            {
                return _Age;
            }
            set
            {
                OnAgeChanging(value);
                ReportPropertyChanging("Age");
                _Age = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Age");
                OnAgeChanged();
            }
        }
        private global::System.String _Age;
        partial void OnAgeChanging(global::System.String value);
        partial void OnAgeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Gender
        {
            get
            {
                return _Gender;
            }
            set
            {
                OnGenderChanging(value);
                ReportPropertyChanging("Gender");
                _Gender = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Gender");
                OnGenderChanged();
            }
        }
        private global::System.String _Gender;
        partial void OnGenderChanging(global::System.String value);
        partial void OnGenderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MarriedStatus
        {
            get
            {
                return _MarriedStatus;
            }
            set
            {
                OnMarriedStatusChanging(value);
                ReportPropertyChanging("MarriedStatus");
                _MarriedStatus = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MarriedStatus");
                OnMarriedStatusChanged();
            }
        }
        private global::System.String _MarriedStatus;
        partial void OnMarriedStatusChanging(global::System.String value);
        partial void OnMarriedStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CHome
        {
            get
            {
                return _CHome;
            }
            set
            {
                OnCHomeChanging(value);
                ReportPropertyChanging("CHome");
                _CHome = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CHome");
                OnCHomeChanged();
            }
        }
        private Nullable<global::System.Int32> _CHome;
        partial void OnCHomeChanging(Nullable<global::System.Int32> value);
        partial void OnCHomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CMobile
        {
            get
            {
                return _CMobile;
            }
            set
            {
                OnCMobileChanging(value);
                ReportPropertyChanging("CMobile");
                _CMobile = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CMobile");
                OnCMobileChanged();
            }
        }
        private Nullable<global::System.Int32> _CMobile;
        partial void OnCMobileChanging(Nullable<global::System.Int32> value);
        partial void OnCMobileChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Regdatetime
        {
            get
            {
                return _Regdatetime;
            }
            set
            {
                OnRegdatetimeChanging(value);
                ReportPropertyChanging("Regdatetime");
                _Regdatetime = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Regdatetime");
                OnRegdatetimeChanged();
            }
        }
        private global::System.String _Regdatetime;
        partial void OnRegdatetimeChanging(global::System.String value);
        partial void OnRegdatetimeChanged();

        #endregion



        public static object Tolist { get; set; }
    }

    #endregion

    
}
